[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self' https://*.netlify.app https://*.firebaseapp.com https://*.firebase.com https://*.google.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.firebaseapp.com https://*.firebase.com https://*.google.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https: wss:; frame-src 'self' https://*.firebaseapp.com https://*.firebase.com;"

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://spacegang.me/*"
  to = "https://spacegang.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.spacegang.me/*"
  to = "https://spacegang.me/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.spacegang.me/*"
  to = "https://spacegang.me/:splat"
  status = 301
  force = true
